#!/bin/bash

MIDIFILE=$1
MP3FILE=$2

#if [ ! -f $1 ] ; then
#echo "File $1 doesn't exist"
#exit ;
#fi

timidity -Ow -o - $MIDIFILE | lame - $MP3FILE

YEAR=`date +%Y`
COMMENT="Generated by Theor"

if [ $3 ] ; then
SONG=$3 ;
else
SONG="A Theor Ditty" ;
fi

URL="http://theortunes.com/"
ALBUM="TheorTunes"
ARTIST="Theor"

id3v2 --WOAR $URL --WOAS $URL --WPUB $URL -c "$COMMENT" -t "$SONG" -y $YEAR -T 1 -A "$ALBUM" -a "$ARTIST" $MP3FILE
